CREATE SEQUENCE ALUMNO_PK_SEQ START WITH 3 INCREMENT BY 1;
CREATE TABLE t_persona ( 
   id INT  PRIMARY KEY NOT NULL, 
   nombre VARCHAR(50) NOT NULL, 
   apellido VARCHAR(50) NOT NULL
);
CREATE TABLE t_alumno ( 
--   identifier INT AUTO_INCREMENT PRIMARY KEY NOT NULL, 
--   identifier INT PRIMARY KEY NOT NULL, 
   identifier INT DEFAULT ALUMNO_PK_SEQ.nextval PRIMARY KEY NOT NULL, 
   name VARCHAR(50) NOT NULL, 
   surname VARCHAR(50) NOT NULL
);
